defaults: &defaults
  # Yelp API v2
  YelpV2:
      :client_credential_key:    86ypn4Dpn4ohLwMF_f24qw
      :client_credential_secret: 92_sq_DgnNeTiHF96upfP_KHlEI
      :token_credential_key:     Mm7BAz8uK0_a1LCYTOJDwWIaMkpuIUzc
      :token_credential_secret:  K0o42jJQL9HeeH2YUiRtpC3yFdc
  Twilio: &Twilio
    # your Twilio authentication credentials
    ACCOUNT_SID: ACe04542bb0bb52dd68d5ed9e03b87ef99
    ACCOUNT_TOKEN: ce45261ee3ced1c7c3af8deb41fddf93

    # version of the Twilio REST API to use
    API_VERSION: 2010-04-01

    # base URL of this application
    BASE_URL: http://staging.mojo.co/sms

    # Outgoing Caller ID you have previously validated with Twilio
    CALLER_ID: (415) 236-3526 # used for development outgoing and staging outgoing/incoming, incoming on http://staging.mojo.co/sms.xml
  s3:
    access_key_id: AKIAII5L2KWAARSQ2VHA
    secret_access_key: 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
  images:
    male: guy
    both: person
    female: girl
  CampaignMonitor: &CampaignMonitor
    APIKey: 8d91618b9b1e76f00886f14cff94ed51
    APIClientID: cc363600fe3afcc2ce53e8d6dc1e06d2
    UserListID: 83d1738e8ac10d8395473a3788ebf4ff        # production list
    SubscribersListID: fc5a863e5f5458e584f17375ba166c2e # production list
  

development:
  <<: *defaults
  bucket: media-development.mojo.co
  smtp:
    address: smtp.gmail.com
    port: 587
    domain: mojo.co
    authentication: plain
    user_name: mailer@mojo.co
    password: br8pRasw
    enable_starttls_auto: Yes # converted to boolean by YAML?
  CampaignMonitor:
    <<: *CampaignMonitor
    UserListID: 695d28f3964f7ba53b7f25b4b2012578

test:
  <<: *defaults

staging:
  <<: *defaults
  bucket: media-staging.mojo.co
  CampaignMonitor:
    <<: *CampaignMonitor
    UserListID: b7e379ec11135f36e07fefdab03825e6

production:
  <<: *defaults
  bucket: media.mojo.co
  Twilio:
    <<: *Twilio
    CALLER_ID: (415) 728-0905 # for production only, incoming on http://mojo.co/sms.xml
