defaults: &defaults
  # Yelp API v2
  YelpV2:
      :client_credential_key:    86ypn4Dpn4ohLwMF_f24qw
      :client_credential_secret: 92_sq_DgnNeTiHF96upfP_KHlEI
      :token_credential_key:     Mm7BAz8uK0_a1LCYTOJDwWIaMkpuIUzc
      :token_credential_secret:  K0o42jJQL9HeeH2YUiRtpC3yFdc
  Twilio:
    # your Twilio authentication credentials
    ACCOUNT_SID: ACe04542bb0bb52dd68d5ed9e03b87ef99
    ACCOUNT_TOKEN: ce45261ee3ced1c7c3af8deb41fddf93

    # version of the Twilio REST API to use
    API_VERSION: 2010-04-01

    # base URL of this application
    BASE_URL: http://staging.mojo.co/sms

    # Outgoing Caller ID you have previously validated with Twilio
    CALLER_ID: (415) 236-3526
  s3:
    access_key_id: AKIAII5L2KWAARSQ2VHA
    secret_access_key: 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
  images:
    male: guy
    both: person
    female: girl
  

development:
  <<: *defaults
  bucket: dev-media.mojo.co
  smtp:
    address: smtp.gmail.com
    port: 587
    domain: mojo.co
    authentication: plain
    user_name: mailer@mojo.co
    password: br8pRasw
    enable_starttls_auto: Yes # converted to boolean by YAML?

test:
  <<: *defaults

staging:
  <<: *defaults
  bucket: media.mojo.co #media.mojo.co

production:
  <<: *defaults
